name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is merged or manual trigger
        if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}
   
      - uses: actions/checkout@v3
          
      - name: Use release drafter
        id: draft_release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: echo env
        run: |
          echo "${{ steps.draft_release.outputs.id }}"
          echo "${{ steps.draft_release.outputs.body }}"
          echo "${{ steps.draft_release.outputs.name }}"
          echo "${{ steps.draft_release.outputs.tag_name }}"
          
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload "${{ steps.draft_release.outputs.tag_name }}" README.md
