name: Release

on:
  create:
    branches:
      - release*
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v3
          
      - name: Use release drafter
        id: draft_release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: echo env
        run: |
          echo "${{ steps.draft_release.outputs.id }}"
          echo "${{ steps.draft_release.outputs.body }}"
          echo "${{ steps.draft_release.outputs.name }}"
          echo "${{ steps.draft_release.outputs.tag_name }}"
          
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete-asset "${{ steps.draft_release.outputs.tag_name }}" README.md --yes || true
          gh release upload "${{ steps.draft_release.outputs.tag_name }}" README.md
